DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS RATE;
DROP TABLE IF EXISTS RENTAL;

CREATE TABLE CUSTOMER
(
    CustID INTEGER NOT NULL,
    Name VARCHAR(160) NOT NULL,
    Phone VARCHAR(15) NOT NULL,

    CONSTRAINT PK_Customer PRIMARY KEY (CustID)
);

CREATE TABLE VEHICLE
(
    VehicleID VARCHAR(30) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    Year VARCHAR(4) NOT NULL,
    Type INTEGER NOT NULL,
    Category INTEGER NOT NULL,

    CONSTRAINT PK_Vehicle PRIMARY KEY (VehicleID),

    FOREIGN KEY (Type) REFERENCES RATE (Type)
    ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE RATE
(
    Type INTEGER NOT NULL,
    Category INTEGER NOT NULL,
    Weekly INTEGER NOT NULL,
    Daily INTEGER NOT NULL,

    CONSTRAINT PK_Rate PRIMARY KEY (Type, Category)
);

CREATE TABLE RENTAL
(
    CustID INTEGER NOT NULL,
    VehicleID INTEGER NOT NULL,
    StartDate DATE NOT NULL,
    OrderDate DATE NOT NULL,
    RentalType INTEGER NOT NULL,
    Qty INTEGER NOT NULL,
    ReturnDate DATE NOT NULL,
    TotalAmount INTEGER NOT NULL,
    PaymentDate DATE NOT NULL,

    CONSTRAINT PK_Rental PRIMARY KEY (CustID, VehicleID, StartDate),

    FOREIGN KEY (CustID) REFERENCES CUSTOMER (CustID)
    ON DELETE CASCADE ON UPDATE CASCADE

    FOREIGN KEY (VehicleID) REFERENCES VEHICLE (VehicleID)
    ON DELETE CASCADE ON UPDATE CASCADE
);
